### ISSUE TITLE
CloudBlob.Exists() throws instead of returning false

### ISSUE THREAD

**Issue by kunchenguid** [Azure/azure-storage-net#168]
When calling CloudBlob.Exists() on a non-existent blob, it threw the 404 WebException instead of returning null.

**Comment by pemari-msft** [comment]
Hi @kunchenguid,

Can you provide more information? We wrap all WebExceptions in StorageExceptions and so I'm surprised this is occurring. What platform are you targeting and what version are you using? Is it a consistent repro? I wasn't able to repro myself locally.

By the way, it shouldn't return null, it should return false, right?

**Comment by kunchenguid** [comment]
thanks for looking into this so quickly. i'm targeting .net framework 4.5 and i'm using the storage sdk version 5.0.0. i'm surprised as well but it's a consistent repro. let me create an isolated project just to repro this issue and send it to you.

**Comment by kunchenguid** [comment]
weird... when i created a separate project, i couldn't repro this. let me dig further...

**Comment by pemari-msft** [comment]
I'll close this for now as no repro. Please feel free to let me know if you do end up finding something else!

**Comment by Eonasdan** [comment]
I'm getting this error with v 6.2 and v7 of the WindowsAzure.Storage nuget packages:

![image](https://cloud.githubusercontent.com/assets/1006516/15152177/4863f194-16a2-11e6-89cf-6ea3acb86ee5.png)

**Comment by pemari-msft** [comment]
Interesting. Can you please share a requestID, account name, and timeframe of the failing request? Feel free to share this privately to Ascl [at] microsoft.com

 Do you have a consistent repro? Or is it transient?

**Comment by Eonasdan** [comment]
@pemari-msft sent subject: "Re: azure-storage-net/issues/168"

**Comment by pemari-msft** [comment]
I'm unable to repro and everything on the service side looks correct -- is this repro consistent for you? Do you have all of your dependencies set up correctly? Can you enable [Client Logging](https://msdn.microsoft.com/en-us/library/azure/dn782839.aspx) and provide logs? Can you provide a stack trace?

**Comment by pemari-msft** [comment]
We have seen this happen sometimes when the container doesn't exist. Closing again as we were unable to get a repro. Please do reopen if you can provide more info.

**Comment by yarinsn** [comment]
I got this error a lot yesterday, especially with freshly created blobs

**Comment by pemari-msft** [comment]
Can you provide more information, such as a fiddler trace, client side logs, a repro, or a request ID?

The exception stack trace would be especially helpful. Thanks!

**Comment by yarinsn** [comment]
debugging it as we speak so tell me if you need more info:

System.Net.WebException occurred
  HResult=0x80131509
  Message=The remote server returned an error: (404) Not Found.
  Source=System
  StackTrace:
   at System.Net.HttpWebRequest.GetResponse()

Headers:
+		Headers	{Transfer-Encoding: chunked
x-ms-request-id: 0e31d3de-0001-004e-63d3-a92bb2000000
x-ms-version: 2016-05-31
Access-Control-Expose-Headers: x-ms-request-id,Server,x-ms-version,Content-Length,Date,Transfer-Encoding
Access-Control-Allow-Origin: *
Date: Fri, 31 Mar 2017 04:01:44 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0

}	System.Net.WebHeaderCollection

**Comment by erezvani1529** [comment]
Hi @yarinsn,

Which framework are you targeting? and would you please share your repro code?

Thanks,
Elham

**Comment by tkjagadheesh** [comment]
I'm also facing this issue, it only occurs when the function is called from a web API, the same function works fine when it's called through a console app.

**Comment by tkjagadheesh** [comment]
private bool IsFileShareExists(string cloudFileShare, string dirName, string accountName, string accountKey)
        {
            var storageAccount = new CloudStorageAccount(new StorageCredentials(accountName, accountKey), true);
            var fileClient = storageAccount.CreateCloudFileClient();
            var share = fileClient.GetShareReference(cloudFileShare);
            return share.Exists();
        }

**Comment by abhikum** [comment]
I am seeing the same issue in WindowsAzure.Storage 8.4.0 Exists() throws 404 exception instead of returning false. I am trying from C# console app
![blob](https://user-images.githubusercontent.com/9576880/35934972-eaec588c-0bf3-11e8-9bce-b128f8da69c3.JPG)

**Comment by cdhemant** [comment]
I am facing the same issue with WindowsAzure.Storage  9.1.0.

even for deleteifexists it gives 404 error

**Comment by h-arslaniqbal** [comment]
This issue may occur if container/fileshare etc name is not valid. Suppose filename that I am passing is 'abc:', then .Exists() will return BadRequest instead of false.

**Comment by Greeng0** [comment]
I'm seeing a similar issue, getting a StorageException when calling ExistsAsync on the root of the share, even though the share itself passed its own ExistsAsync check. Using version 10.0.0.0 of Microsoft.Azure.Storage.File

![image](https://user-images.githubusercontent.com/1999393/55886426-b6598000-5b79-11e9-83eb-e138affec894.png)

**Comment by pemari-msft** [comment]
This was a bug that was found and fixed in a 10.0.1 release yesterday. Can you try updating and see if that resolves your issue? Sorry for the inconvenience.

**Comment by Greeng0** [comment]
@pemari-msft  Yes that fixes it, thank you!

**Comment by marionzr** [comment]
I still have this problem in the version 11.1.3
![image](https://user-images.githubusercontent.com/47438990/84493797-c473c680-ac7e-11ea-84cb-f2fd9f769720.png)

Unfortunately, I don't have extra details since the code works fine in my local machine (Docker) but fails on the Azure DevOps Pipeline
