### ISSUE TITLE
ArgumentOutOfRangeException regression with storage lib 8.1.3

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#471]
Microsoft.WindowsAzure.Storage.StorageException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:line 77
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndFastCopyTo[T](IAsyncResult fastCopyToResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 185
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 115
Request Information
RequestID:
RequestDate:
StatusMessage:

**Comment by erezvani1529** [comment]
Thanks @IlyaGrebnov Ilya for reporting this issue. We have the fix ready to go out in a hotfix tomorrow.

**Comment by erezvani1529** [comment]
Fixed in 8.1.4.

Thanks again @IlyaGrebnov.

**Comment by Yonisha** [comment]
@erezvani1529 I upgraded to 8.1.4 and I still see the issue. any recommendation?
